LESSONS = [
    {
        "slug": "variables-types",
        "title": "Variables et types",
        "description": "Découvre comment stocker des valeurs.",
        "content": "En Python, une variable stocke une valeur (texte, nombre, booléen...).",
        "example": "a = 2\nb = 3\nprint(a + b)",
        "exercise": {
            "title": "Addition simple",
            "prompt": "Crée deux variables x=7 et y=5 puis affiche leur somme.",
            "starter_code": "# Écris ton code ici\n",
            "validator": "expect_output",
            "expected_output": "12",
            "xp": 20,
        },
    },
    {
        "slug": "loops-for",
        "title": "Boucles for",
        "description": "Répète une action automatiquement.",
        "content": "Une boucle for parcourt une séquence de valeurs.",
        "example": "for i in range(1, 11):\n    print(i)",
        "exercise": {
            "title": "Afficher 1 à 10",
            "prompt": "Affiche les nombres de 1 à 10 chacun sur une ligne.",
            "starter_code": "# Utilise range\n",
            "validator": "expect_lines",
            "expected_lines": [str(i) for i in range(1, 11)],
            "xp": 25,
        },
    },
    {
        "slug": "conditions-if-else",
        "title": "Conditions if/else",
        "description": "Prends des décisions dans ton code.",
        "content": "if/else permet d'exécuter du code selon une condition.",
        "example": "n = 4\nif n % 2 == 0:\n    print('pair')\nelse:\n    print('impair')",
        "exercise": {
            "title": "Pair ou impair",
            "prompt": "Définis n=9 et affiche 'pair' ou 'impair'.",
            "starter_code": "n = 9\n",
            "validator": "expect_output",
            "expected_output": "impair",
            "xp": 25,
        },
    },
    {
        "slug": "lists",
        "title": "Listes",
        "description": "Manipule des collections d'éléments.",
        "content": "Une liste est ordonnée et modifiable.",
        "example": "fruits = ['pomme', 'banane']\nfruits.append('kiwi')\nprint(fruits)",
        "exercise": {
            "title": "Ajouter un élément",
            "prompt": "Crée une liste [1,2,3], ajoute 4, puis affiche la liste.",
            "starter_code": "# Crée ta liste\n",
            "validator": "expect_output",
            "expected_output": "[1, 2, 3, 4]",
            "xp": 30,
        },
    },
    {
        "slug": "functions",
        "title": "Fonctions",
        "description": "Réutilise du code proprement.",
        "content": "Une fonction encapsule une logique que tu peux réutiliser.",
        "example": "def carre(n):\n    return n * n\nprint(carre(5))",
        "exercise": {
            "title": "Fonction carré",
            "prompt": "Crée une fonction carre(n) qui retourne le carré de n, puis affiche carre(6).",
            "starter_code": "def carre(n):\n    # retourne le carré\n    pass\n\n",
            "validator": "expect_output",
            "expected_output": "36",
            "xp": 35,
        },
    },
]

LESSON_MAP = {lesson["slug"]: lesson for lesson in LESSONS}
