-- Run in Supabase SQL editor
create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  total_xp int not null default 0,
  streak int not null default 0,
  last_activity date,
  badges text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_slug text not null,
  completed boolean not null default false,
  xp_earned int not null default 0,
  completed_at date,
  unique (user_id, lesson_slug)
);

alter table profiles enable row level security;
alter table progress enable row level security;

create policy "Users can read own profile"
  on profiles for select using (auth.uid() = user_id);
create policy "Users can update own profile"
  on profiles for update using (auth.uid() = user_id);
create policy "Users can insert own profile"
  on profiles for insert with check (auth.uid() = user_id);

create policy "Users can read own progress"
  on progress for select using (auth.uid() = user_id);
create policy "Users can write own progress"
  on progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
